spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/futbol-api
    username: grupo-d-dapp
    password: 12345678
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # o validate, create-drop, etc.
    show-sql: true
    properties:
      hibernate:
        format_sql: true
